/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-background': '#e5e2e1',
        surface: '#131313',
        error: '#ffb4ab',
        outline: '#8d909d',
        background: '#131313',
        'on-tertiary-fixed-variant': '#005313',
        'on-primary-fixed-variant': '#00429c',
        'surface-container-high': '#2a2a2a',
        'on-primary-container': '#a1bbff',
        'primary-fixed-dim': '#b0c6ff',
        'surface-container-low': '#1c1b1b',
        'inverse-on-surface': '#313030',
        'on-secondary-fixed-variant': '#872100',
        'outline-variant': '#434652',
        'surface-container-highest': '#353534',
        'surface-container': '#201f1f',
        'tertiary-fixed': '#98f994',
        'error-container': '#93000a',
        'on-primary-fixed': '#001945',
        'secondary-fixed': '#ffdbd1',
        'surface-variant': '#353534',
        'on-tertiary': '#00390a',
        'surface-dim': '#131313',
        secondary: '#ffb5a0',
        'inverse-surface': '#e5e2e1',
        tertiary: '#7ddc7a',
        'on-primary': '#002d6f',
        'tertiary-container': '#005915',
        'on-tertiary-fixed': '#002204',
        'on-tertiary-container': '#73d171',
        'primary-fixed': '#d9e2ff',
        'secondary-fixed-dim': '#ffb5a0',
        primary: '#b0c6ff',
        'on-error-container': '#ffdad6',
        'secondary-container': '#d33a01',
        'on-error': '#690005',
        'inverse-primary': '#2b5bb5',
        'on-secondary-container': '#fff7f5',
        'on-secondary': '#5f1500',
        'on-secondary-fixed': '#3b0900',
        'surface-bright': '#393939',
        'on-surface': '#e5e2e1',
        'surface-tint': '#b0c6ff',
        'surface-container-lowest': '#0e0e0e',
        'primary-container': '#0d47a1',
        'on-surface-variant': '#c3c6d4',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'stack-sm': '8px',
        'stack-md': '16px',
        gutter: '24px',
        margin: '32px',
        'container-padding': '24px',
        'touch-target': '48px',
      },
      fontFamily: {
        'body-lg': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'display-md': ['Inter', 'sans-serif'],
        'data-mono': ['JetBrains Mono', 'monospace'],
        'label-md': ['JetBrains Mono', 'monospace'],
        'display-lg-mobile': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'display-md': ['36px', { lineHeight: '44px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'data-mono': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '500' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
